### ISSUE TITLE
Example does not work with 1.20 and 1.21

### ISSUE THREAD

**Issue by lnxbil** [saschagrunert/ccli#109]
Hi,

I just built a MWE with your example and wanted to build in 1.21 and 1.20 in Docker:

```
$ docker run -it --rm mcr.microsoft.com/devcontainers/go:1.21-bookworm
```

Then try to compile:

```
root ➜ /go $ mkdir src/ccli-test && cd src/ccli-test

root ➜ /go/src/ccli-test $ wget -q https://raw.githubusercontent.com/saschagrunert/ccli/master/example/main.go

root ➜ /go/src/ccli-test $ go mod init
go: creating new go.mod: module ccli-test
go: to add module requirements and sums:
	go mod tidy

root ➜ /go/src/ccli-test $ go get
go: downloading github.com/urfave/cli v1.22.14
go: downloading github.com/urfave/cli/v2 v2.25.7
go: downloading github.com/saschagrunert/ccli v1.0.1
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: ccli-test imports
	github.com/saschagrunert/ccli/v2: cannot find module providing package github.com/saschagrunert/ccli/v2

root ➜ /go/src/ccli-test $ go get github.com/saschagrunert/ccli/v2
go: module github.com/saschagrunert/ccli@upgrade found (v1.0.1), but does not contain package github.com/saschagrunert/ccli/v2
```

If I use the non-v2-import of `ccli`, I got of course a type mismatch due to the incompatibility from `ccli/v1` with `cli/v2`.

Any hints?

**Comment by saschagrunert** [comment]
Does it now work with the latest `main` branch?

**Comment by lnxbil** [comment]
Sadly no, same problem. I really don't get it, `go.mod` has the `v2` in it, why doesn't it run properly?

If I checkout your git repo and compile the example itself, it works, yet not in another project/folder.

Here is a `Dockerfile` to reproduce the problem:

```Dockerfile
FROM mcr.microsoft.com/devcontainers/go:1.21-bookworm

RUN mkdir src/ccli-test
WORKDIR src/ccli-test

RUN \
    wget -q https://raw.githubusercontent.com/saschagrunert/ccli/master/example/main.go && \
    go mod init

RUN go get
```

Just build to reproduce the error.

**Comment by saschagrunert** [comment]
The v2 branch was missing, now it should work with v2.0.2. :upside_down_face:

**Comment by lnxbil** [comment]
Yes, perfect. Thank you.

**Comment by saschagrunert** [comment]
`v2` is now the default branch, no need for `main`/`master` any more.
